name = "Ferret Lockfile"
grammar = "ferret_lockfile"
path_suffixes = ["ferret.lock"]
first_line_pattern = "^\\s*\\{"
line_comments = []
icon = "json"
tab_size = 2
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
]
