name = "Ferret Manifest"
grammar = "ferret_manifest"
path_suffixes = ["fer.ret"]
first_line_pattern = "^\\s*\\[package\\]"
line_comments = ["# "]
icon = "toml"
tab_size = 2
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
]
